---
- include_tasks: check_preconditions.yml

- name: store facts
  include_tasks: store-facts.yml
  when: store_facts | default(true)

- name: start monitoring
  include_tasks: monitoring-start.yml
  when: enable_monitoring | default(false)

- include_tasks: '{{ pre_tasks_file }}'
  when: 'pre_tasks_file is defined'

- name: get number of repetitions
  set_fact:
    num_repetitions: "{{ (num_repetitions | default([])) + [ item ] }}"
  with_sequence: count="{{ repetitions | default(1) }}"

- name: execute each benchmark
  include_tasks: run-bench.yml
  with_items: '{{ benchmarks }}'
  loop_control:
    loop_var: benchmark

- name: stop monitoring
  include_tasks: monitoring-stop.yml
  when: enable_monitoring | default(false)

- include_tasks: '{{ post_tasks_file }}'
  when: 'post_tasks_file is defined'
...
